//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /// &lt;summary&gt;
        ///    /// &lt;%name%&gt;.
        ///    /// &lt;/summary&gt;
        ///    public sealed class &lt;%class%&gt; : Crc
        ///    {
        ///        private static byte[] _table;
        ///
        ///        /// &lt;summary&gt;
        ///        /// Initializes a new instance of the &lt;%class%&gt; class.
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;withTable&quot;&gt;Calculations with the table.&lt;/param&gt;
        ///        public &lt;%class%&gt;(bool withTable = true) : base(GetEngine(&quot;&lt;%name%&gt;&quot;, withTable))
        ///        {
        ///        }
        /// 
        ///        private static CrcEngine GetEngine(string algorithmName, bool [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Templ {
            get {
                return ResourceManager.GetString("Templ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test(new &lt;%class%&gt;(), input, true);
        ///            Test(new &lt;%class%&gt;(false), input);
        ///            Test(new CrcCustom(&lt;%width%&gt;, &lt;%refin%&gt;, &lt;%refout%&gt;, &lt;%poly%&gt;, &lt;%init%&gt;, &lt;%xorout%&gt;), input);
        ///            Test(new CrcCustom(&lt;%width%&gt;, &lt;%refin%&gt;, &lt;%refout%&gt;, &quot;&lt;%poly%&gt;&quot;, &quot;&lt;%init%&gt;&quot;, &quot;&lt;%xorout%&gt;&quot;, core1), input);
        ///            Test(new CrcCustom(&lt;%width%&gt;, &lt;%refin%&gt;, &lt;%refout%&gt;, &quot;&lt;%poly%&gt;&quot;, &quot;&lt;%init%&gt;&quot;, &quot;&lt;%xorout%&gt;&quot;, core2), input); 的本地化字符串。
        /// </summary>
        internal static string templ2 {
            get {
                return ResourceManager.GetString("templ2", resourceCulture);
            }
        }
    }
}
